### ISSUE TITLE
Toggling shortcut CTRL+Y does not work on Windows/Linux

### ISSUE THREAD

**Issue by dbudke** [mesoneer-ag/camunda-modeler-property-info-plugin#1]
The overlay toggling shortcut CTRL+Y does not work on Windows/Linux. It overlaps with the "redo" shortcut on Windows and Linux.

**Comment by itsmefox** [comment]
Hi @dbudke 
Thx for your bug submit.
We are searching for a new meaningful and "free" shortcut. Stay tuned for the next release.

**Comment by BrianHaller** [comment]
Hi @dbudke 
I changed the shortcut from "CommandOrControl+Y" to "Alt+Y"
Greets
Brian
