### ISSUE TITLE
Add option to show element ID as a label.

### ISSUE THREAD

**Issue by StephenOTT** [mesoneer-ag/camunda-modeler-property-info-plugin#10]
At times you want to see the element IDs on all elements.  Could be for writing migrations or checking errors, etc.

Would be great to have a the ability to toggle the showing of element IDs.

**Comment by itsmefox** [comment]
Design for elementID-badge:
![elementid](https://user-images.githubusercontent.com/2861746/29523323-f619dab4-868c-11e7-9b76-4d1f57cd6410.png)

All elementID-badges should be toggleable with a menu entry for elementID-badge toggle.

**Comment by StephenOTT** [comment]
Looks nice

**Comment by ruslan-moskovenko** [comment]
Element ids added in the new release
