### ISSUE TITLE
Selection Markers?

### ISSUE THREAD

**Issue by StephenOTT** [mesoneer-ag/camunda-modeler-property-info-plugin#15]
have a use case that i thought might be a good use for property-info-plugin.

Often we are sharing/printing a BPMN and there are specific sections we want to highlight.

So say there was 5 activities we wanted to label/highlight.  
We dont want to make changes to the actual BPMN as its version controlled with GIT.

But something such as doing a multiple select, or going into "select" mode that would like you click N number of elements which would then be numbered, or possibly show the IDs, or some sort of numbers/text based identifier.

The purpose is that once the BPMN is exported to an image, there is a write-up that occurs explaining the each of the elements.

Thoughts?

**Comment by ruslan-moskovenko** [comment]
Hi @StephenOTT 

Thank you for another idea. 
I don't think this would be a scope of this plugin, but definitely a good idea for the respective one.
