### ISSUE TITLE
Feedback about usability and bug report

### ISSUE THREAD

**Issue by mburke84** [mesoneer-ag/camunda-modeler-property-info-plugin#16]
Hi,
we've gotten the following feedback from a Camunda customer about this plugin:

> Usability:
> * Die Overlays werden beim Herauszoomen aus dem Prozessmodell komplett ausgeblendet
> * Ich würde mir wünschen, dass zumindest die Information, dass hier Properties gefüllt sind, auf irgendeine Art und Weise erhalten bleiben, auch beim herauszoomen
> * Genauso würde ein Filter zum Aktivieren/Deaktivieren für einzelne Arten von Properties helfen
> Bugs:
> * Startet man den Camunda Modeler nicht über die camunda-modeler.exe (Sondern über einen Klick auf eine BPMN Datei) im Programmordner, so wird das Highlighting des Plugins nicht im Prozess Modell angezeigt

Thanks and best regards,
Mat

**Comment by ruslan-moskovenko** [comment]
Hi @mburke84 

Thank you for the feedback.
Currently I cannot reproduce this issues on my side.
Filter is not in the scope of the latest release but may definitely be for next one.
