### ISSUE TITLE
Modeler looses it's history when this plugin is installed

### ISSUE THREAD

**Issue by meepza** [mesoneer-ag/camunda-modeler-property-info-plugin#18]
The modeler seems to loose it's most recent open file history when this plugin is installed. Toggling it on and off has no effect either. If you close the modeler with a model open and displayed, and then re-invoke the modeler, it opens without any model. It should open with the most recent open model displayed and all other models that were open at the time in additional tabs.

**Comment by ruslan-moskovenko** [comment]
Hi @meepza 

Please try saving bpmn files before closing them in order to keep the changes.

Kind regards
