### ISSUE TITLE
Asynchpoints missing

### ISSUE THREAD

**Issue by FO-e-X** [mesoneer-ag/camunda-modeler-property-info-plugin#19]
At CamundaCon 2018 the plugin was able to show a lot of things, including asynch points (blue square). I downloaded the current version from GIT and included it into the modeller and... asynch points are missing.

Was the demo at CamundaCon 2108 running with a newer version or do I have to modifiy some configuration somehow?

**Comment by dbudke** [comment]
You can download the version shown at the CamundaCon from the releases tab:
https://github.com/umb/camunda-modeler-property-info-plugin/releases/tag/0.0.3-beta

**Comment by FO-e-X** [comment]
Ah, thanks... I just started with git and missed the release-tab. I thought, root is allways the current version... Now it works. Thanks a lot.
