### ISSUE TITLE
Add Async Info to overlay

### ISSUE THREAD

**Issue by StephenOTT** [mesoneer-ag/camunda-modeler-property-info-plugin#2]
Add Async Info to overlay

On all items including gateways

**Comment by itsmefox** [comment]
Hi @StephenOTT 
There is already a plugin which supports this information: [bpmn-js-plugin-transaction-boundaries](https://github.com/camunda/camunda-modeler-plugins/tree/master/bpmn-js-plugin-transaction-boundaries). We will check if we also provide such a function.

**Comment by itsmefox** [comment]
Design for transactions:
![transaction](https://user-images.githubusercontent.com/2861746/29523740-3de83952-868e-11e7-93bc-54fcfebb6c59.png)

The transaction element has to be located at the entry or exit of every sequence flow. There should also be a toggle menu item for these elements.

**Comment by StephenOTT** [comment]
@patrickboesch what about "exclusive" marker?

**Comment by benhoffmann** [comment]
Hi @patrickboesch , I like the idea of displaying transaction boundaries. However, the proposed design can easily be mixed up with BPMN message flows. How about using colored lines or something else instead?

**Comment by nikku** [comment]
[This bpmn-js extension](https://github.com/bpmn-io/bpmn-js-transaction-boundaries) shows transaction markers as a colored line. Maybe it is an idea worth picking up? 

![image](https://user-images.githubusercontent.com/58601/44469794-8e3c0180-a628-11e8-8b07-c437492f5b10.png)

**Comment by ruslan-moskovenko** [comment]
Implemented in the new Release
