### ISSUE TITLE
Conflict with registering plugin name

### ISSUE THREAD

**Issue by Ichigo85** [mesoneer-ag/camunda-modeler-property-info-plugin#20]
Please change registering plugin name on PropertyInfoPlugin.js file. The name exported (clientPlugin) is a bit overused because it's [camunda-modeler-plugin-example](https://github.com/camunda/camunda-modeler-plugin-example), 'propertyInfoPlugin' is more talkative.

**Comment by ruslan-moskovenko** [comment]
Hi @Ichigo85 

As i can see this change is already applied.

Kind regards
