### ISSUE TITLE
[transactions] show implicit transaction boundaries

### ISSUE THREAD

**Issue by stefanzilske** [mesoneer-ag/camunda-modeler-property-info-plugin#21]
I am using your transactions branch, which shows also transaction boundaries. It would be awesome, if also the implicit transaction boundaries, caused by user tasks and intermediate timer and message catch events, were shown.

**Comment by nikku** [comment]
For a full list of possible boundaries you may checkout [camunda-transaction-boundaries](https://github.com/bpmn-io/camunda-transaction-boundaries), too.

**Comment by ruslan-moskovenko** [comment]
Hi @stefanzilske 

Transactions are now available in the latest (0.0.3) release.

Kind regards
