### ISSUE TITLE
Error reported when using with Modeler 4.x

### ISSUE THREAD

**Issue by pinussilvestrus** [mesoneer-ag/camunda-modeler-property-info-plugin#24]
Hello 👋🏻

Starting with Camunda Modeler 4.0.0 an error raised a couple of times (more than 6k error events) inside our error tracking tools which we identified from this plugin (cf. https://github.com/camunda/camunda-modeler/issues/2001)

```text
TypeError: Cannot read property 'extensionElements' of undefined
  at addStyle (~/build/client-bundle.js:124:71)
  at None (~/build/client-bundle.js:44:13)
  at None (~/build/client-bundle.js:2153:43)
```

I reproduced it when I tried to trigger the [overlays for a participant with no processRef](https://github.com/umb/camunda-modeler-property-info-plugin/blob/master/client/PropertyInfoPlugin.js#L123). Hard to reproduce though, maybe there is an easier way to reproduce.

**Comment by ruslan-moskovenko** [comment]
Hi @pinussilvestrus 

This issue is fixed in the latest release.

Thank you and kind regards
