### ISSUE TITLE
Display all documentation "post-it" with text

### ISSUE THREAD

**Issue by fml2** [mesoneer-ag/camunda-modeler-property-info-plugin#26]
Hello,

as of now, the plugin draws a yellow corner for the diagram elements that have a non empty documentation. In order to see the text, one has to move the mouse over the yellow corner.

It would be cool if it was possible to display all the texts at the same time so that one can see and read all the documentation notes without having to move the mouse.

Ideally, this would be a toggle switch ("show all" / "hide all").

Thank you.

**Comment by ruslan-moskovenko** [comment]
Hi @fml2 

Thank you for your suggestion. 
I'm afraid that having multiple comments next to each other may cause them to overlap. 
Dont think we will implement it for now, but lets see what we can do for the next release.

Kind regards

**Comment by fml2** [comment]
Even if it's possible to toggle them (display all at once / display only the current one)?
