### ISSUE TITLE
Execution Listeners (L) on Sequence Flows

### ISSUE THREAD

**Issue by julrichkieffer** [mesoneer-ag/camunda-modeler-property-info-plugin#29]
In reviewing another's BPMN diagram, I discovered that Sequence Flows can also associate Execution Listeners. However, as I've come to rely on this lovely plugin to highlight implementation aspects, it doesn't indicate execution listeners when these are applied to a sequence flow.

**Comment by moritzwiechers** [comment]
hi @julrichkieffer,

In our project analyzing bpmn diagramms and changing them is our every day work. We often ran into the problem, that a connection was recreated or changed and the listener got dropped by mistake. 

This repo seems to be inactive. So I created a [fork](https://github.com/moritzwiechers/camunda-modeler-property-info-plugin/tree/master) and added the functionality to show badges on SequenceFlows.

Maybe it could be usefull for you too.

**Comment by ruslan-moskovenko** [comment]
Hi @julrichkieffer 

Sequence Flow implementation is now available in the new (0.0.3) release.

Kind regards
