### ISSUE TITLE
Tasks: Extension icon is not removed from overlay when Extension is deleted.

### ISSUE THREAD

**Issue by StephenOTT** [mesoneer-ag/camunda-modeler-property-info-plugin#3]
![screen shot 2017-07-07 at 11 26 24 am](https://user-images.githubusercontent.com/1994838/27964700-312a8d0a-6307-11e7-8751-3c416b99fb7e.png)

**Comment by itsmefox** [comment]
Hi @StephenOTT 
The bug should be fix now 👍
