### ISSUE TITLE
Plugin Breaks Camunda Modeler When Using Collapsed Participants

### ISSUE THREAD

**Issue by philippfromme** [mesoneer-ag/camunda-modeler-property-info-plugin#30]
Using this plugin can break the Camunda Modeler. To reproduce this issue:

1. Use this plugin
2. Create a collapsed participant

The error occurs because a collapsed participant does not have a `processRef` property which the plugin doesn't account for: https://github.com/mesoneer-ag/camunda-modeler-property-info-plugin/blob/master/client/PropertyInfoPlugin.js#L123

The error message: `TypeError: Cannot read properties of undefined (reading 'extensionElements')`

**Comment by philippfromme** [comment]
Is there any chance we'll ever see this fixed? We're getting hundreds of errors caused by this plugin. You might want to archive it if you don't plan on maintaining it anymore.

**Comment by ruslan-moskovenko** [comment]
Hi @philippfromme 

Thank you for reporting this.
This issue is now fixed in the latest (0.0.3) release.

Kind regards
