### ISSUE TITLE
Inactive Repo for highly required extension

### ISSUE THREAD

**Issue by jonathanlukas** [mesoneer-ag/camunda-modeler-property-info-plugin#31]
Hello @itsmefox ,

this repo seems to be inactive for 5 years now. There are several issues and PRs to be handled. What would think of moving this repo to the community hub?

Here is a doc that shows you how: https://github.com/camunda-community-hub/community/blob/main/transferring-extensions.md

Please feel free to reach out if you have any questions.

**Comment by itsmefox** [comment]
I'm sorry, but I am no longer working for this company, and I am not able to assist with this matter.
But I think it would be awesome if this repo could be moved to the community hub and receive some updates & love.

**Comment by jonathanlukas** [comment]
@dbudke could you please initiate this?

**Comment by ruslan-moskovenko** [comment]
Hi @jonathanlukas 

We are back now and going to maintain this one.

Kind regards
