### ISSUE TITLE
Add Sequence Flow Condition Type Icon

### ISSUE THREAD

**Issue by StephenOTT** [mesoneer-ag/camunda-modeler-property-info-plugin#4]
It is common to accidentally delete configuration of a sequence flow because you do not know it there unless you are clicking into all of the sequence flows.

Would be helpful to have a icon on sequence flows that show what condition type (if any) has been selected.

**Comment by itsmefox** [comment]
Hi @StephenOTT 
This feature will be part of the sequence flow integration and is in the pipeline for our next release.

**Comment by moritzwiechers** [comment]
hi @StephenOTT,
surely your request is outdated, but just in case it's still up to date:

In our project analyzing bpmn diagramms and changing them is our every day work. We often ran into the problem, that a connection was recreated or changed and the listener got dropped by mistake.

This repo seems to be inactive. So I created a [fork](https://github.com/moritzwiechers/camunda-modeler-property-info-plugin/tree/master) and added the functionality to show badges on SequenceFlows.

Maybe it could be usefull for you too.

**Comment by ruslan-moskovenko** [comment]
New badges for sequence flow are now available in the new release
