### ISSUE TITLE
Element Documentation Icon

### ISSUE THREAD

**Issue by StephenOTT** [mesoneer-ag/camunda-modeler-property-info-plugin#5]
Icon to represent that the element documentation field has content.
Might be better to make this a secondary toggle.

edit: could be good for Pool's Process Documentation as well

**Comment by itsmefox** [comment]
Design for the implementation:
![documentation-1](https://user-images.githubusercontent.com/2861746/29314662-3f24e2e4-81bf-11e7-94b2-720b48f78290.png)
![documentation-2](https://user-images.githubusercontent.com/2861746/29314666-408a37e2-81bf-11e7-927a-eafd73628df2.png)

**Comment by itsmefox** [comment]
New colors for the box:
#FFDE00
#D38C17

**Comment by StephenOTT** [comment]
GREAT!!!!!!
