### ISSUE TITLE
Pool executable icon

### ISSUE THREAD

**Issue by StephenOTT** [mesoneer-ag/camunda-modeler-property-info-plugin#6]
Add icon indicating if Pool is executable
.

**Comment by StephenOTT** [comment]
This actually might be better as a "Not Executable" AND a Executable icons.

**Comment by itsmefox** [comment]
Maybe something like this and a corresponding not executable icon:

![group](https://user-images.githubusercontent.com/2861746/28923486-888e07a4-785e-11e7-8258-a2841fbc88ca.png)
