### ISSUE TITLE
Plugin should not be enabled/toggled-on by default

### ISSUE THREAD

**Issue by StephenOTT** [mesoneer-ag/camunda-modeler-property-info-plugin#8]
Currently the plugin is enabled by default.  It should be disabled by default.

**Comment by itsmefox** [comment]
Hi @StephenOTT 
As mentioned in the ReadMe one new feature will be ability to save the current toggle state automatically in the preferences of the modeler. In this case it is necessary to have it enabled by default to provide a perfect user experience at the first launch of the plugin.
